import type { Metadata } from "next";
import { Varela, Geist_Mono } from "next/font/google";
import "./globals.css";

const varela = Varela({
  variable: "--font-varela",
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "New GlassTab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${varela.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-background min-h-dvh font-sans text-foreground antialiased">{children}</body>
    </html>
  );
}
